server:
   port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
      hostname: localhost












#
#spring:
#  cloud:
#   gateway:
#      routes:
#        -id: LoginApi-2
#        url: lb://LoginApi-2
#        predicates:
#          -Path=/user/**
#
#
#  application:
#    name: service-registration
#
#
#eureka:
#  client:
#    service-url:
#        defaultZone: http://localhost:8761/eureka/
#
